debug: true
server:
  port: 8094

redis:
  host: localhost
  port: 6379

mysql:
  host: "localhost"
  port: 3306
  user: root
  password: ...

  db: "chatnio"

secret: ... # jwt secret
auth:
  access: ...
  salt: ...
  sign: ...

openai:
  gpt3:
    endpoint: https://api.openai.com
    apikey: sk-...|sk-...

  gpt4:
    endpoint: https://api.openai.com
    apikey: sk-...|sk-...

slack:
  bot_id: ...
  token: ...
  channel: ...

claude:
  apikey: ...
  endpoint: ...

sparkdesk:
  app_id: ...
  api_secret: ...
  api_key: ...
  model: generalv2
  endpoint: wss://spark-api.xf-yun.com/v2.1/chat

palm2:
  endpoint: ...
  apikey: ...

bing:
  # learn more at https://github.com/Deeptrain-Community/chatnio-bing-service
  endpoint: ...
  secret: ...

zhipuai:
  endpoint: https://open.bigmodel.cn
  apikey: ...
