mysql:
  db: chatnio
  host: localhost
  password: chatnio123456
  port: 3306
  user: root
  tls: false

redis:
  host: localhost
  port: 6379
  db: 0
  password: ""


secret: secret
serve_static: true

server:
  port: 8094
system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5

wechat_work:
  enabled: false
  corp_id: ""     # 企业微信CorpID
  agent_id: ""    # 应用AgentID
  secret: ""      # 应用Secret
  redirect_uri: "" # 回调URL，如：https://yourdomain.com/api/wechat/callback
