debug: true
server:
  port: 8094

redis:
  host: localhost
  port: 6379

openai:
  anonymous: sk-xxxxxx|sk-xxxxxx|sk-xxxxxx
  anonymous_endpoint: https://api.openai.com/v1
  user: sk-xxxxxx|sk-xxxxxx|sk-xxxxxx
  user_endpoint: https://api.openai.com/v1
  image: sk-xxxxxx|sk-xxxxxx|sk-xxxxxx
  image_endpoint: https://api.openai.com/v1
  gpt4: sk-xxxxxx|sk-xxxxxx|sk-xxxxxx
  gpt4_endpoint: https://api.openai.com/v1

  reverse: gpt-4  # cf reverse
  pro: ey...|ey...|ey...
  pro_endpoint: .../imitate/v1

claude:
  key: ...
  endpoint: ...

mysql:
  host: localhost
  port: 3306
  user: root
  password: ...

  db: chatnio

secret: ...
auth:
  access: ...
  salt: ...
